### PR TITLE
Issue #172 Making sure that private key id can be provided as well

### PR DESCRIPTION
**Pull request by hferentschik**
Based on pull request #173. Addresses issue #172

### CODE REVIEW

**Comment by hferentschik** [comment]
If we are good, feel free to merge.

**Comment by hferentschik** [comment]
@vpavlin wdyt shall I go ahead and merge and build the image?

**Comment by vpavlin** [comment]
Yes

**Comment by hferentschik** [comment]
Cool. Building and uploading image. In the office, so it won't take too long.

**Pull request merged**
