### PR TITLE
Fix #308 removed empty keys from deploymentconfig

### LINKED ISSUE #308: Remove unwanted empty keys from openshift template
A couple of empty `resources` keys can be dropped from openshift resource yaml

### PR DESCRIPTION
**Pull request by hrishin**
- Removed empty `resources` from deploymentconfig.spec.strategy
- Removed empty `resources` from deploymentconfig.spec.containers

#308

### CODE REVIEW

**Comment by kishansagathiya** [comment]
@hrishin Travis build is failing
This is due to our commit message rules
Use this format
```
Issue #NUMBER Start with capital, Title<50 chars

Leave a line. Wrap it with 72 chars in a line
```

**Comment by hrishin** [comment]
@sthaha @kishansagathiya could you review it, pelase?

**Comment by sthaha** [comment]
Going to use admin right to merge this.

**Pull request merged**
