### PR TITLE
[WIP] Issue #165 Too many redirects

### LINKED ISSUE #165: Too many redirects
Proxy often gets into redirect loop which results in too many redirects error - after showing this error, browser redirects to the Jenkins successfully.

The issue probably lies in how we work with cookies and generally verify if user is logged in

### PR DESCRIPTION
**Pull request by kishansagathiya**
- HandleJenkinsUIRequest code had way too many self-redirect and buggy cookie handling
- This change to HandleJenkinsUIRequest proposed a much simpler logic and tries to get rid of JenkinsIdled cookie

Fixes #165

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @kishansagathiya for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by kishansagathiya** [comment]
Build is failing because of https://github.com/golang/lint/issues/397

**Comment by kishansagathiya** [comment]
When the it redirects to jenkins it redirects to `https://jenkins-ksagathi-preview-jenkins.b542.starter-us-east-2a.openshiftapps.com/`. Who makes sure that the URL shows `https://jenkins.openshift.io` instead?

**Comment by kishansagathiya** [comment]
https://www.reddit.com/r/golang/comments/3loqtq/how_to_redirect_a_user_after_login/

**Pull request closed without merging**
