### PR TITLE
Fix #293 Misspellings in the comment and doc

### LINKED ISSUE #293: Fix misspellings in the comment and doc
```
 % misspellings * openshift/**/* cmd/**/* internal/**/*                 
README.md:135: seperate -> "separate"
internal/jenkinsapi/jenkinsapi.go:74: reponse -> "response"
internal/router/router_test.go:88: Doesnt -> "Doesn't"
internal/util/logging/request.go:10: seperated -> "separated"
internal/util/logging/request.go:10: seperated -> "separated"
```

### PR DESCRIPTION
**Pull request by chmouel**
Correct misspells error reported by https://pypi.org/project/misspellings/.

### CODE REVIEW

**Comment by kishansagathiya** [comment]
[test]

**Comment by chmouel** [comment]
[test]

**Comment by chmouel** [comment]
[test]

**Comment by chmouel** [comment]
[test]

**Pull request merged**
